version: '3.0'
services:
  db: 
    image: mongo:5.0
    container_name: crm-vendor-db
    restart: always
    ports:
      - 27017:27017    
    volumes:
      - crm-vendor-data:/data/db

volumes:
  crm-vendor-data:
    driver: local